version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: America/Mexico_City
    labels:
      - dependabot
      - github-actions dependencies
