packages:
  - "libs/*"
  - "apps/*"

overrides:
  vitest: "^3.1.0"

peerDependencyRules:
  allowedVersions:
    vitest: ">=3"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - esbuild
  - lmdb
  - msgpackr-extract
