packages:
  - "libs/*"
  - "apps/*"
  - "tools/*"

minimumReleaseAge: 1440

allowBuilds:
  "@nestjs/core": true
  "@parcel/watcher": true
  "@tailwindcss/oxide": true
  core-js: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true

overrides:
  fast-uri: ">=3.1.2"
  path-to-regexp: ">=8.4.0"

minimumReleaseAgeExclude: []

auditConfig:
  ignoreCves: []
