import type { ProfileData, LinkData, SkillCategoryData } from '@vh/profile';
import type { GitHubRepo } from '../github/github.schemas';

export function renderHeader(profile: ProfileData): string {
  const badges = [
    'Node.js-339933?logo=nodedotjs',
    'TypeScript-3178C6?logo=typescript',
    'Angular-DD0031?logo=angular',
    'React-61DAFB?logo=react&logoColor=black',
    'AWS-232F3E?logo=amazonwebservices',
    'Azure-0078D4?logo=microsoftazure',
    'NestJS-E0234E?logo=nestjs',
    '.NET-512BD4?logo=dotnet',
  ]
    .map(
      (b) =>
        `![](https://img.shields.io/badge/${b}&style=flat&logoColor=white)`,
    )
    .join(' ');

  return `# ${profile.name}\n\n**${profile.headline}** | ${profile.location}\n\n${badges}`;
}

export function renderSummary(profile: ProfileData): string {
  return `## About\n\n${profile.summary}`;
}

export function renderSkills(skills: readonly SkillCategoryData[]): string {
  if (skills.length === 0) return '';

  const rows = skills
    .map((cat) => `| **${cat.category}** | ${cat.skills.join(', ')} |`)
    .join('\n');

  return `## Skills\n\n| Category | Technologies |\n| --- | --- |\n${rows}`;
}

export function renderFeaturedProjects(repos: readonly GitHubRepo[]): string {
  const withDescription = repos.filter((r) => r.description);
  if (withDescription.length === 0) return '';

  const rows = withDescription
    .map((r) => {
      const lang = r.language ? ` \`${r.language}\`` : '';
      const stars =
        r.stargazers_count > 0 ? ` ⭐ ${String(r.stargazers_count)}` : '';

      return `| [**${r.name}**](${r.html_url}) | ${r.description}${lang}${stars} |`;
    })
    .join('\n');

  return `## Featured Projects\n\n| Project | Description |\n| --- | --- |\n${rows}`;
}

export function renderCTA(links: readonly LinkData[]): string {
  const items = links
    .filter((l) => l.url.startsWith('http'))
    .map((l) => `[${l.label}](${l.url})`);

  if (items.length === 0) return '';

  return `## Let's Connect\n\n${items.join(' | ')}`;
}

export function renderFooter(): string {
  return `---\n\n*Generated by [virgenherrera](https://github.com/virgenherrera/virgenherrera) · [Developer Guide](docs/README-DEV.md)*`;
}
