import type { ProfileData, LinkData } from "@virgenherrera/profile";
import type { GitHubRepo } from "../github/github.schemas.ts";

export function renderHeader(profile: ProfileData): string {
  return `# ${profile.name}\n\n**${profile.headline}** | ${profile.location}`;
}

export function renderSummary(profile: ProfileData): string {
  const sentences = profile.summary.split(/(?<=\.)\s+/);
  const preview = sentences.slice(0, 2).join(" ");

  return `## About\n\n${preview}`;
}

export function renderFeaturedProjects(repos: readonly GitHubRepo[]): string {
  if (repos.length === 0) {
    return "";
  }

  const cards = repos
    .map((repo) => {
      const lang = repo.language ? ` \`${repo.language}\`` : "";
      const stars =
        repo.stargazers_count > 0 ? ` ⭐ ${repo.stargazers_count}` : "";
      const desc = repo.description ?? "No description";

      return `- [**${repo.name}**](${repo.html_url}) — ${desc}${lang}${stars}`;
    })
    .join("\n");

  return `## Featured Projects\n\n${cards}`;
}

export function renderCTA(links: readonly LinkData[]): string {
  const linkItems = links
    .filter((link) => link.url.startsWith("http"))
    .map((link) => `[${link.label}](${link.url})`)
    .join(" | ");

  if (!linkItems) {
    return "";
  }

  return `## Let's Connect\n\n${linkItems}`;
}

export function renderFooter(): string {
  return `---\n\n*Generated by [virgenherrera](https://github.com/virgenherrera/virgenherrera) · [Developer Guide](README-DEV.md)*`;
}
