import type {
  ProfileData,
  ExperienceData,
  EducationData,
  SkillCategoryData,
  LanguageData,
  LinkData,
} from "@virgenherrera/profile";

function renderHeader(profile: ProfileData): string {
  return `# ${profile.name}\n\n**${profile.headline}**\n\n${profile.location}`;
}

function renderSummary(summary: string): string {
  return `## About\n\n${summary}`;
}

function renderSkills(skills: SkillCategoryData[]): string {
  if (skills.length === 0) {
    return "";
  }

  const categories = skills
    .map(
      (cat: SkillCategoryData) =>
        `- **${cat.category}**: ${cat.skills.join(", ")}`,
    )
    .join("\n");

  return `## Skills\n\n${categories}`;
}

function renderExperience(experience: ExperienceData[]): string {
  if (experience.length === 0) {
    return "";
  }

  const entries = experience
    .map((exp: ExperienceData) => {
      const period = exp.endDate
        ? `${exp.startDate} - ${exp.endDate}`
        : `${exp.startDate} - Present`;
      const techLine =
        exp.technologies.length > 0
          ? `\n\n  Technologies: ${exp.technologies.join(", ")}`
          : "";

      return `### ${exp.role} @ ${exp.company}\n\n*${period}*\n\n${exp.description}${techLine}`;
    })
    .join("\n\n");

  return `## Experience\n\n${entries}`;
}

function renderEducation(education: EducationData[]): string {
  if (education.length === 0) {
    return "";
  }

  const entries = education
    .map((edu: EducationData) => {
      const period = edu.endDate
        ? `${edu.startDate} - ${edu.endDate}`
        : `${edu.startDate} - Present`;

      return `- **${edu.degree}** in ${edu.field} — ${edu.institution} (*${period}*)`;
    })
    .join("\n");

  return `## Education\n\n${entries}`;
}

function renderLanguages(languages: LanguageData[]): string {
  if (languages.length === 0) {
    return "";
  }

  const list = languages
    .map((lang: LanguageData) => `- **${lang.language}**: ${lang.proficiency}`)
    .join("\n");

  return `## Languages\n\n${list}`;
}

function renderLinks(links: LinkData[]): string {
  if (links.length === 0) {
    return "";
  }

  const list = links
    .map((link: LinkData) => `- [${link.label}](${link.url})`)
    .join("\n");

  return `## Links\n\n${list}`;
}

function renderContact(email: string | undefined): string {
  if (!email) {
    return "";
  }

  return `## Contact\n\n- Email: [${email}](mailto:${email})`;
}

function renderFooter(): string {
  return `---\n\n*Generated by [virgenherrera-cli](https://github.com/virgenherrera/virgenherrera)*`;
}

export function renderReadme(profile: ProfileData): string {
  const sections: string[] = [
    renderHeader(profile),
    renderSummary(profile.summary),
    renderSkills(profile.skills),
    renderExperience(profile.experience),
    renderEducation(profile.education),
    renderLanguages(profile.languages),
    renderLinks(profile.links),
    renderContact(profile.email),
    renderFooter(),
  ];

  const content = sections.filter(Boolean).join("\n\n");

  return `${content}\n`;
}
